### ISSUE TITLE
Error when freeswitch load mod_event_kafka

### ISSUE THREAD

**Issue by denialhaq** [voiceip/mod_event_kafka#8]
Hi , Currently I am trying to use this module to integrate our freeswitch using kafka.
i already compile and get  a mod_event_kafka.so file.

When i try to load this module, i got this error.

<img width="717" alt="Screen Shot 2021-11-25 at 09 36 30" src="https://user-images.githubusercontent.com/46884796/143517482-3c7e6a57-b956-42a3-bd28-f56c04eec7af.png">

Is there anything i had wrong on implementing this module?

Thank you, any suggestions or input will be very helpful

**Comment by kingster** [comment]
Which version of FreeSWITCH are you running/compiling against? And is it the same machine on which you are trying to run this?

**Comment by denialhaq** [comment]
FreeSWITCH version: 1.10.6-release-18-1ff9d0a60e~64bit (-release-18-1ff9d0a60e 64bit)

That is the freeswitch version currently i am running with and yes, it is using same machine

**Comment by kingster** [comment]
Your logs says that the mod_event_kafka is trying to connect to kafka broker running on localhost on port 9092. Can you confirm if you have kafka broker running on the same machine?

**Comment by denialhaq** [comment]
Yes, currently kafka broker runnung on localhost using port 9092. If i create broker and try using kafkacat i can reach the topic as image shown below 
<img width="624" alt="Screen Shot 2021-11-25 at 19 54 33" src="https://user-images.githubusercontent.com/46884796/143446612-4b70eaf3-931f-4933-bdb2-b5d8c0d6ee11.png">

**Comment by denialhaq** [comment]
Hi, i hope you are doing well.
Just want to add more detail, we run freeswitch and kafka on the same mechine (that is why i am using localhost) and also kafka using the same port 9092.
Is there advise how you integrate this freeswitch kafka module?

**Comment by kingster** [comment]
Hi

I was unable to replicate your error. This is what I attempted

I booted up a fresh VM (debian 10) and installed the latest freeswitch using this [steps](https://freeswitch.org/confluence/display/FREESWITCH/Debian+10+Buster)

```
root@buster:/# dpkg -l | grep freeswitch | head
ii  freeswitch                        1.10.7~release~19~883d2cb662~buster-1~buster+1 amd64        Cross-Platform Scalable Multi-Protocol Soft Switch
```

Installed the `kafka_2.11-2.1.1` following this [steps](https://www.digitalocean.com/community/tutorials/how-to-install-apache-kafka-on-debian-10)

And installed the mod_event_kafka using the following set of commands

```
apt-get -y install libfreeswitch-dev librdkafka-dev libz-dev libssl-dev pkg-config
make
make install
```

Then tried to load the module into freeswitch 

```
freeswitch@buster> load mod_event_kafka
+OK Reloading XML
+OK

2021-11-29 06:51:03.086906 99.47% [INFO] switch_stun.c:897 External ip address detected using STUN: 122.182.199.215
2021-11-29 06:51:03.326970 99.47% [INFO] switch_stun.c:897 External ip address detected using STUN: 122.182.199.215
2021-11-29 06:51:03.347164 99.47% [INFO] mod_enum.c:887 ENUM Reloaded
2021-11-29 06:51:03.347164 99.47% [INFO] switch_time.c:1430 Timezone reloaded 1750 definitions
2021-11-29 06:51:03.347164 99.47% [INFO] mod_event_kafka.cpp:72 KafkaEventPublisher Initialising...
2021-11-29 06:51:03.347164 99.47% [INFO] mod_event_kafka.cpp:60 event_kafka.conf loaded [brokers: localhost:9092, prefix: topic_name, buffer-size: 16]
2021-11-29 06:51:03.347164 99.47% [INFO] mod_event_kafka.cpp:102 KafkaEventPublisher Topic : topic_name_buster
2021-11-29 06:51:03.347164 99.47% [DEBUG] mod_event_kafka.cpp:219 Subscribed to events
2021-11-29 06:51:03.347164 99.47% [DEBUG] mod_event_kafka.cpp:224 Module loaded completed
2021-11-29 06:51:03.347164 99.47% [CONSOLE] switch_loadable_module.c:1768 Successfully Loaded [mod_event_kafka]
```

And I see the module successfully loading. 

Can you please double check your configuration/VM settings? or try it on a fresh VM or please share the steps to reproduce the error.

**Comment by denialhaq** [comment]
Hi Thank you for your response and advice.

Based on your steps, i do some troubleshoot and install a fresh installation. 

i can running the module get event using kafka after upgrade the system and freeswitch version.

**Comment by kingster** [comment]
I am glad that you were able to resolve the issue. Any chance you found what was the cause of the issue? 

This module is only for publishing event from freeswitch. However you can use the mod_esl api's to programmatically control free switch.

**Comment by denialhaq** [comment]
Ok, noted. 

Actually I am not sure what cause of the issue.

i did `apt upgrade` on recent system and freeswitch automatically upgrade from 1.10.6 to 1.10.7, then everything work.
